# Copyright (c) 2023-2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
from __future__ import annotations

from abc import ABC, abstractmethod
from ast import literal_eval as str_to_tuple
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar, Generic, Literal, TypeVar, cast

from yaml import CSafeDumper, CSafeLoader, dump, load

from pyavd._utils import get
from pyavd.j2filters import natural_sort

if TYPE_CHECKING:
    from pyavd._eos_designs.shared_utils import SharedUtils

T_ValueType = TypeVar("T_ValueType", int, str)

FILE_HEADER = """\
# This file is auto-generated by AVD eos_designs.
# When there is a merge conflict for this file, rebase the branch, accept all current changes for this file, and re-run AVD.
"""

PoolType = Literal["node_id_pools"]
PoolKey = tuple[str | None, ...]
AssignmentKey = tuple[str | None, ...]


@dataclass
class PoolAssignment(Generic[T_ValueType]):
    key: AssignmentKey
    value: T_ValueType
    accessed: bool = False

    def as_dict(self) -> dict[str, str | T_ValueType]:
        """Returns a dict representing the object."""
        return {"key": str(self.key), "value": self.value}

    @classmethod
    def from_dict(cls, data: dict) -> PoolAssignment[T_ValueType]:
        """Returns assignment from file data."""
        if not isinstance(data, dict):
            msg = f"Invalid type '{type(data)}'. Expected a dict."
            raise TypeError(msg)

        if not isinstance(key_str := data.get("key"), str):
            msg = f"Invalid type '{type(key_str)}'. Expected a str."
            raise TypeError(msg)
        key = str_to_tuple(key_str)

        # Triggering a key error on purpose if the value is missing
        return cls(key=key, value=data["value"])


@dataclass
class Pool(Generic[T_ValueType]):
    """One Pool of resources. Currently only supporting a pool of Integers."""

    collection: PoolCollection[T_ValueType]
    pool_key: PoolKey
    assignments: dict[AssignmentKey, PoolAssignment[T_ValueType]]

    def _is_value_available(self, value: T_ValueType) -> bool:
        if self.collection.value_type is int and isinstance(value, int):
            collection = cast(PoolCollection[int], self.collection)
            assignments = cast(dict[AssignmentKey, PoolAssignment[int]], self.assignments)
            existing_ids = {assignment.value for assignment in assignments.values()}
            return not (value in existing_ids or value < collection.min_value or (collection.max_value is not None and value > collection.max_value))

        # currently we only support int pools
        return False

    def _next_available(self) -> T_ValueType:
        if self.collection.value_type is int:
            collection = cast(PoolCollection[int], self.collection)
            assignments = cast(dict[AssignmentKey, PoolAssignment[int]], self.assignments)
            existing_ids = {assignment.value for assignment in assignments.values()}
            available_ids = set(range(collection.min_value, len(existing_ids) + 2)) - existing_ids
            next_available = next(iter(available_ids))
            if collection.max_value is not None and next_available > collection.max_value:
                msg = (
                    f"No available values found within '{self.collection.pools_key}' with key '{self.pool_key}' "
                    f"and range {collection.min_value}-{collection.max_value}."
                )
                raise ValueError(msg)
            return cast(T_ValueType, next_available)

        msg = f"Currently we only support pools of Integers. Got {self.collection.value_type}."
        raise NotImplementedError(msg)

    def get_assignment(self, key: AssignmentKey, requested_value: T_ValueType | None = None) -> PoolAssignment[T_ValueType]:
        """
        Returns the assignment for the key if found in the pool.

        Otherwise a new entry is inserted into the pool and returned.

        If 'requested_value' is given and available in the pool, any existing assignment will be updated and returned.
        For new assignments this value will be used.
        """
        if key not in self.assignments:
            # No existing assignment. Use the requested value if given and available. Otherwise use next available.
            new_assignment_value = requested_value if requested_value is not None and self._is_value_available(requested_value) else self._next_available()
            self.assignments[key] = self.collection.assignment_cls(key=key, value=new_assignment_value, accessed=True)
            self.collection.changed = True
        elif requested_value is not None and requested_value != self.assignments[key].value and self._is_value_available(requested_value):
            # Existing assignment but not with the requested value. Change the existing assignment to the requested_value.
            self.assignments[key] = self.collection.assignment_cls(key=key, value=requested_value, accessed=True)
            self.collection.changed = True
        else:
            # Existing item
            self.assignments[key].accessed = True

        return self.assignments[key]

    def _remove_stale_assignments(self) -> None:
        """
        Remove stale assignments. An assignment is deemed stale if "accessed" is not True. Sets parent .changed if it removed anything.

        Note: This method is called from the parent collection and should _not_ be called manually.
        """
        len_before = len(self.assignments)
        self.assignments = {key: assignment for key, assignment in self.assignments.items() if assignment.accessed}
        self.collection.changed = self.collection.changed or len_before != len(self.assignments)

    def as_dict(self) -> dict:
        """Returns a dict representing the object."""
        return {
            "pool_key": str(self.pool_key),
            "assignments": natural_sort([assignment.as_dict() for assignment in self.assignments.values()], sort_key="value"),
        }

    @classmethod
    def from_dict(cls, data: dict, collection: PoolCollection) -> Pool[T_ValueType]:
        """Returns pool from file data."""
        if not isinstance(data, dict):
            msg = f"Invalid type '{type(data)}'. Expected a dict."
            raise TypeError(msg)

        if not isinstance(pool_key_str := data["pool_key"], str):
            msg = f"Invalid type '{type(pool_key_str)}'. Expected a str."
            raise TypeError(msg)
        pool_key = str_to_tuple(pool_key_str)

        if not isinstance(pool_assignments := data["assignments"], list):
            msg = f"Invalid type '{type(pool_assignments)}'. Expected a list."
            raise TypeError(msg)

        return cls(
            collection=collection,
            pool_key=pool_key,
            assignments={assignment.key: assignment for item in data["assignments"] if (assignment := collection.assignment_cls.from_dict(item))},
        )


@dataclass
class PoolCollection(ABC, Generic[T_ValueType]):
    """
    Collection of similar Pool instances indexed by a tuple.

    We will maintain a collection of pools per file.
    """

    pools_file: Path
    pools_key: str
    _pools: dict[PoolKey, Pool] = field(init=False)
    pool_cls: type[Pool[T_ValueType]]
    assignment_cls: type[PoolAssignment[T_ValueType]]
    value_type: type[T_ValueType]
    min_value: T_ValueType
    max_value: T_ValueType | None = None
    changed: bool = False

    def __post_init__(self) -> None:
        """Try to load data from the pools_file into _pools. If the file is missing, we just set a blank pools."""
        if not self.pools_file.exists():
            self._pools = {}

        file_data = load(self.pools_file.read_text(encoding="UTF-8"), Loader=CSafeLoader)
        if not isinstance(file_data, dict) or self.pools_key not in file_data:
            self._pools = {}
            return

        try:
            self._pools = self._pools_from_list(file_data[self.pools_key])
        except (TypeError, KeyError, ValueError) as e:
            msg = f"An error occurred during parsing of '{self.pools_file}': {e.__class__.__name__}: {e}"
            raise TypeError(msg) from e

    def _pools_from_list(self, data: list) -> dict[PoolKey, Pool]:
        """Returns pools from file data."""
        if not isinstance(data, list):
            msg = f"Invalid type '{type(data)}'. Expected a list."
            raise TypeError(msg)
        return {pool.pool_key: pool for item in data if (pool := self.pool_cls.from_dict(item, collection=self))}

    def get_pool(self, pool_key: PoolKey) -> Pool[T_ValueType]:
        """
        Returns the pool for the given key if found in the collection.

        Otherwise a new pool is inserted into the collection and returned.
        """
        if pool_key not in self._pools:
            self._pools[pool_key] = self.pool_cls(collection=self, pool_key=pool_key, assignments={})
            self.changed = True

        return self._pools[pool_key]

    def _remove_stale_assignments(self) -> None:
        """
        Remove stale assignments from all pools in the collection and remove empty pools afterwards.

        Note: This method is called from the parent pool manager and should _not_ be called manually.
        """
        len_before = len(self._pools)
        [pool._remove_stale_assignments() for pool in self._pools.values()]
        self._pools = {pool_key: pool for pool_key, pool in self._pools.items() if pool.assignments}
        self.changed = self.changed or len_before != len(self._pools)

    def as_list(self) -> list[dict]:
        """Returns a list of dicts representing the object."""
        return natural_sort([pool.as_dict() for pool in self._pools.values()], sort_key="pool_key")

    def save_updates(self, dumper_cls: type = CSafeDumper) -> bool:
        """
        Save data if anything changed. Returns a boolean telling if anything was changed.

        Calls self._remove_stale_assignments first to ensure we save the cleaned data.

        Data is sorted to ensure a consistent layout.
        """
        self._remove_stale_assignments()
        if not self.changed:
            return False

        if not self.pools_file.exists():
            # Try to create the dir and file.
            self.pools_file.parent.mkdir(mode=0o775, parents=True, exist_ok=True)
            self.pools_file.touch(mode=0o664)

        self.pools_file.write_text(FILE_HEADER + dump({self.pools_key: self.as_list()}, Dumper=dumper_cls))
        self.changed = False
        return True

    @staticmethod
    @abstractmethod
    def _pool_key_from_shared_utils(shared_utils: SharedUtils) -> PoolKey:
        """Returns the pool key to use for tthis device."""

    @staticmethod
    @abstractmethod
    def _pool_file_from_shared_utils(output_dir: Path, shared_utils: SharedUtils) -> Path:
        """Returns the file to use for this device."""

    @staticmethod
    @abstractmethod
    def _assignment_key_from_shared_utils(shared_utils: SharedUtils) -> AssignmentKey:
        """Returns the assignment key to use for this device."""


@dataclass()
class NodeIdPoolCollection(PoolCollection):
    pools_key: str = "node_id_pools"
    pools: dict[PoolKey, Pool[int]] = field(default_factory=dict)
    pool_cls: type[Pool[int]] = Pool[int]
    assignment_cls: type[PoolAssignment[int]] = PoolAssignment[int]
    value_type: type = int
    min_value: int = 1

    @staticmethod
    def _pool_key_from_shared_utils(shared_utils: SharedUtils) -> PoolKey:
        """Returns the pool key to use for this device."""
        return (shared_utils.fabric_name, shared_utils.inputs.dc_name, shared_utils.inputs.pod_name, shared_utils.type)

    @staticmethod
    def _pool_file_from_shared_utils(output_dir: Path, shared_utils: SharedUtils) -> Path:
        """Returns the file to use for this device."""
        fabric_name = shared_utils.fabric_name
        default_id_file = output_dir.joinpath(f"data/{fabric_name}-ids.yml")
        return Path(get(shared_utils.hostvars, "fabric_numbering.node_id.pools_file", default=default_id_file))

    @staticmethod
    def _assignment_key_from_shared_utils(shared_utils: SharedUtils) -> AssignmentKey:
        """Returns the assignment key to use for this device."""
        return (shared_utils.hostname,)


class PoolManager:
    """
    Class used to handle pooled resources.

    This class is imported and initialized once in eos_designs_facts
    and given to shared_utils for each device.
    """

    _pool_types: ClassVar = {"node_id_pools": NodeIdPoolCollection}

    _output_dir: Path
    _pool_collections: dict[PoolType, dict[Path, PoolCollection]]

    """PoolCollection collections keys by file path."""

    def __init__(self, output_dir: Path) -> None:
        self._output_dir = output_dir
        self._pool_collections = {}
        self._changed_pool_files = {}

    def save_updated_pools(self, dumper_cls: type = CSafeDumper) -> bool:
        """
        Save data if anything changed. Returns a boolean telling if anything was changed.

        Note that this will also prune any unused/stale allocations (not requested for since initialization) and remove empty pools.
        """
        any_changes = False
        for pools_files_map in self._pool_collections.values():
            changes_for_this_pool_type = [pool_collection.save_updates(dumper_cls) for pool_collection in pools_files_map.values()]
            any_changes = any_changes or any(changes_for_this_pool_type)
        return any_changes

    def get_pool(self, pool_type: PoolType, shared_utils: SharedUtils) -> Pool:
        """Returns the pool of the given type for this device. Pool will be autocreated if missing."""
        if pool_type not in self._pool_types:
            msg = f"Invalid pool type '{pool_type}'. Expected one of {', '.join(self._pool_types.keys())}"
            raise ValueError(msg)

        pools_files_map = self._pool_collections.setdefault(pool_type, {})
        pools_cls = self._pool_types[pool_type]
        pools_file = pools_cls._pool_file_from_shared_utils(self._output_dir, shared_utils)

        if pools_file not in pools_files_map:
            # Not using setdefault since initializing the pool will read from file.
            pools_files_map[pools_file] = pools_cls(pools_file=pools_file)
        pool_collection = pools_files_map[pools_file]

        pool_key = pools_cls._pool_key_from_shared_utils(shared_utils)
        return pool_collection.get_pool(pool_key)

    def get_assignment(self, pool_type: PoolType, shared_utils: SharedUtils, requested_value: int | str | None = None) -> int:
        """
        Returns the assignment value for this device for the given pool type. Assignment and pool will be autocreated if missing.

        Args:
            pool_type: Currently only supports "node_id_poools".
            shared_utils: Instance of SharedUtils for the device.
            requested_value: A requested value to assign to the device if available. Existing assignment will be changed if possible.
                There are no guarantees that this value will be assigned, so the caller should check and handle accordingly.
        """
        pool = self.get_pool(pool_type, shared_utils)
        key = self._pool_types[pool_type]._assignment_key_from_shared_utils(shared_utils)
        return pool.get_assignment(key, requested_value).value
